baseURL = 'https://syake-salmon.github.io/'
languageCode = 'ja-JP'
title = "Index for syakesalmon"
theme = 'hugo-coder'

paginate = 20

# disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "syakesalmon"
  info = "A Sunday-Coder."
  description = "syakesalmon's personal website"
  keywords = "developer,game"
  avatarurl = "images/avatar.jpg"

  faviconSVG = "favicon.svg"
  favicon_32 = "favicon-32x32.png"
  favicon_16 = "favicon-16x16.png"

  since = 2023

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]
  customRemoteJS = ["https://kit.fontawesome.com/dc213e7fa6.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Bluesky"
  icon = "fa-brands fa-bluesky fa-2x"
  weight = 1
  url = "https://bsky.app/profile/syake.ikesu.blue"
  target = "_blank"
  rel = "noopenner noreferrer"

[[params.social]]
  name = "Tumblr"
  icon = "fa-brands fa-tumblr fa-2x"
  weight = 2
  url = "https://syakesalmon.tumblr.com/"
  target = "_blank"
  rel = "noopenner noreferrer"

[[params.social]]
  name = "Discord"
  icon = "fa-brands fa-discord fa-2x"
  weight = 3
  url = "http://discordapp.com/users/231032349972889610/"
  target = "_blank"
  rel = "noopenner noreferrer"

[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 4
  url = "https://github.com/syake-salmon/"
  target = "_blank"
  rel = "noopenner noreferrer"

[[params.social]]
  name = "Qiita"
  icon = "fa fa-search fa-2x"
  weight = 5
  url = "https://qiita.com/syakesalmon/"
  target = "_blank"
  rel = "noopenner noreferrer"

[[params.social]]
  name = "Xbox"
  icon = "fa-brands fa-xbox fa-2x"
  weight = 6
  url = "https://live.xbox.com/en-US/Profile?gamertag=syakesalmon"
  target = "_blank"
  rel = "noopenner noreferrer"

[[params.social]]
  name = "Twitch"
  icon = "fa fa-twitch fa-2x"
  weight = 7
  url = "https://www.twitch.tv/syakesalmon__/"
  target = "_blank"
  rel = "noopenner noreferrer"
