[params]
  author = "syakesalmon"
  bio = "I code for curiosity and game for joy."

  avatar_tech = "images/avatar-tech.jpg"
  avatar_game = "images/avatar-game.jpg"

[[params.links]]
  name = "GitHub"
  icon = "fa-brands fa-github fa-2x"
  url = "https://github.com/syake-salmon/"
  category = "tech"

[[params.links]]
  name = "Qiita"
  icon = "fa-solid fa-q fa-2x"
  url = "https://qiita.com/syake-salmon/"
  category = "tech"

[[params.links]]
  name = "Bluesky"
  icon = "fa-brands fa-bluesky fa-2x"
  url = "https://bsky.app/profile/syak3.bsky.social"
  category = "tech"

[[params.links]]
  name = "Twitch"
  icon = "fa-brands fa-twitch fa-2x"
  url = "https://www.twitch.tv/8ytefish"
  category = "game"

[[params.links]]
  name = "Xbox"
  icon = "fa-brands fa-xbox fa-2x"
  url = "https://live.xbox.com/en-US/Profile?gamertag=syakesalmon"
  category = "game"

[[params.links]]
  name = "X"
  icon = "fa-brands fa-x-twitter"
  url = "https://x.com/8yteFish"
  category = "game"

# [[params.links]]
#  name = "Discord"
#  icon = "fa-brands fa-discord fa-2x"
#  url = "http://discordapp.com/users/231032349972889610/"
#  category = "game"